from collections import Counter
from .models import CategoryCounts, CompatibilityStatus, MigrationReport

def build_report(plan, generated_ids=(), errors=(), ordering_plan=None):
    counts=Counter(x.status for x in plan.compatibility); types=Counter(x.entity_type for x in plan.compatibility); generated=set(generated_ids)
    required=sorted({value for x in plan.compatibility for value in x.required_mappings})
    renderable={x.entity_id for x in plan.generate}; emitted=generated & renderable
    refs=sorted({ref for item in plan.compatibility for ref in item.documentation_refs})
    version_result="BLOCKING" if plan.blocked else "WARNING" if any(x.version_status!="VERIFIED" for x in plan.compatibility) else "PASS"
    return MigrationReport(source_vendor=plan.source_vendor,target_vendor=plan.target_vendor,total_entities=len(plan.compatibility),exact=counts[CompatibilityStatus.EXACT],supported=counts[CompatibilityStatus.SUPPORTED],partial=counts[CompatibilityStatus.PARTIAL],manual_review=counts[CompatibilityStatus.MANUAL_REVIEW],unsupported=counts[CompatibilityStatus.UNSUPPORTED],version_not_verified=counts[CompatibilityStatus.VERSION_NOT_VERIFIED],categories=CategoryCounts(objects=types["address"]+types["address_group"],services=types["service"]+types["service_group"],interfaces=types["interface"],zones=types["zone"],security_policies=types["security_policy"],nat_policies=types["nat_policy"],routes=types["route"]),warnings=plan.advisories,errors=list(errors)+plan.blocked,required_mappings=required,generated_entities=len(emitted),skipped_entities=len(plan.compatibility)-len(emitted),compatibility=plan.compatibility,names=plan.names,source_version=plan.source_version,target_version=plan.target_version,documentation_refs=refs,version_validation_result=version_result,security_rule_ordering=ordering_plan)