import {useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Workbench} from './components/Workbench';
import {buildOperationRequest,initialSelection,type PlatformSelection} from './platformContext';
import type {Manifest,Operation,Profile,Result} from './types';

const boot=JSON.parse(document.getElementById('configmorph-bootstrap')?.textContent||'{"profiles":[],"maxConfigBytes":104857600}') as {profiles:Profile[];maxConfigBytes:number};

export default function App(){
  const[sourceText,setSourceText]=useState(''),[sourceName,setSourceName]=useState(''),[selection,setSelection]=useState<PlatformSelection>(initialSelection),[detectedVersion,setDetectedVersion]=useState('');
  const[result,setResult]=useState<Result>(),[manifest,setManifest]=useState<Manifest>(),[operation,setOperation]=useState<Operation>(),[error,setError]=useState(''),[stale,setStale]=useState(false);
  const running=Boolean(operation&&!operation.completed&&operation.status!=='FAILED'),selectedSource=useMemo(()=>boot.profiles.find(p=>p.id===selection.source.profileId),[selection.source.profileId]),selectedTarget=useMemo(()=>boot.profiles.find(p=>p.id===selection.target.profileId),[selection.target.profileId]);
  useEffect(()=>{if(!operation||operation.completed||operation.status==='FAILED')return;const controller=new AbortController(),timer=setTimeout(async()=>{try{const next=await api.operation(operation.operation_id,controller.signal);setOperation(next);if(next.result){setResult(next.result);setManifest(undefined);setStale(false)}if(next.status==='FAILED')setError(`${next.stage.replaceAll('_',' ')} failed: ${next.error?.message||'Operation failed'}`)}catch(reason){if(!controller.signal.aborted){const message=String(reason);setError(message);setOperation(current=>current?{...current,status:'FAILED',completed:true,error:{message}}:current)}}},300);return()=>{clearTimeout(timer);controller.abort()}},[operation]);
  async function load(text:string,name:string){if(new TextEncoder().encode(text).length>boot.maxConfigBytes){setError('Configuration exceeds the 100 MiB limit.');return}setSourceText(text);setSourceName(name);setResult(undefined);setManifest(undefined);setStale(false);setError('');try{const detected=await api.detect(text),version=detected.version||'';setDetectedVersion(version);if(version&&selection.source.hardwareId&&!selection.source.osVersion)setSelection(current=>({...current,source:{...current.source,osVersion:version}}))}catch(reason){setError(String(reason))}}
  function hydrate(data:{manifest:Manifest;source_text:string;result:Result}){const r={...data.result,project_id:data.manifest.project_id},source=data.manifest.source,target=data.manifest.target;setManifest(data.manifest);setResult(r);setSourceText(data.source_text);setSourceName(source.filename);setDetectedVersion(source.exact_version);setSelection({domain:source.domain||r.source_profile.domain,source:{vendor:source.vendor||r.source_profile.vendor,hardwareId:source.hardware_id||'',profileId:source.profile_id||r.source_profile.id,osVersion:source.exact_version},target:{vendor:target.vendor||r.target_profile.vendor,hardwareId:target.hardware_id||'',profileId:target.profile_id||r.target_profile.id,osVersion:target.exact_version}});setOperation(undefined);setStale(false);setError('')}
  async function openProject(id:string){try{hydrate(await api.project(id))}catch(reason){setError(String(reason))}}
  async function importProject(file:File){try{const imported=await api.importProject(file);hydrate(await api.project(imported.project_id))}catch(reason){setError(String(reason))}}
  function contextChanged(next:PlatformSelection){setSelection(next);if(result)setStale(true)}
  async function run(){if(!selectedSource||!selectedTarget)return setError('Select source and target profiles.');setError('');setResult(undefined);setManifest(undefined);setStale(false);try{const started=await api.start(buildOperationRequest(sourceText,selection,boot.profiles));setOperation({operation_id:started.operation_id,status:'RUNNING',stage:'VALIDATING_SOURCE',stages:[],elapsed_ms:0})}catch(reason){setError(String(reason))}}
  return <Workbench profiles={boot.profiles} maxConfigBytes={boot.maxConfigBytes} sourceText={sourceText} sourceName={sourceName} selection={selection} detectedVersion={detectedVersion} result={result} manifest={manifest} operation={operation} error={error} stale={stale} running={running} onLoad={load} onRun={run} onOpen={openProject} onImportProject={importProject} onSelection={contextChanged} onUseDetected={()=>contextChanged({...selection,source:{...selection.source,osVersion:detectedVersion}})} onRemove={()=>{setSourceText('');setSourceName('');setDetectedVersion('');setResult(undefined);setManifest(undefined);setOperation(undefined);setStale(false)}}/>;
}
