import {useEffect,useMemo,useState} from 'react';
import {api} from './api';
import {Workbench} from './components/Workbench';
import type {Operation,Profile,Result} from './types';

const boot=JSON.parse(document.getElementById('configmorph-bootstrap')?.textContent||'{"profiles":[],"maxConfigBytes":104857600}') as {profiles:Profile[];maxConfigBytes:number};

export default function App(){
  const [sourceText,setSourceText]=useState(''),[sourceName,setSourceName]=useState(''),[sourceProfile,setSourceProfile]=useState(''),[sourceVersion,setSourceVersion]=useState(''),[targetProfile,setTargetProfile]=useState(''),[targetVersion,setTargetVersion]=useState('');
  const [result,setResult]=useState<Result>(),[operation,setOperation]=useState<Operation>(),[error,setError]=useState(''),[stale,setStale]=useState(false);
  const running=Boolean(operation&&!operation.completed&&operation.status!=='FAILED'),selectedSource=useMemo(()=>boot.profiles.find(p=>p.id===sourceProfile),[sourceProfile]),selectedTarget=useMemo(()=>boot.profiles.find(p=>p.id===targetProfile),[targetProfile]);
  useEffect(()=>{if(!operation||operation.completed||operation.status==='FAILED')return;const controller=new AbortController(),timer=setTimeout(async()=>{try{const next=await api.operation(operation.operation_id,controller.signal);setOperation(next);if(next.result){setResult(next.result);setStale(false)}if(next.status==='FAILED')setError(`${next.stage.replaceAll('_',' ')} failed: ${next.error?.message||'Operation failed'}`)}catch(reason){if(!controller.signal.aborted)setError(String(reason))}},300);return()=>{clearTimeout(timer);controller.abort()}},[operation]);
  async function load(text:string,name:string){if(new TextEncoder().encode(text).length>boot.maxConfigBytes){setError('Configuration exceeds the 100 MiB limit.');return}setSourceText(text);setSourceName(name);setResult(undefined);setStale(false);setError('');try{const detected=await api.detect(text),source=boot.profiles.find(p=>p.source_vendor===detected.vendor&&p.domain===detected.domain),targets=boot.profiles.filter(p=>p.domain===detected.domain&&p.id!==source?.id&&p.target_capability.includes('RENDERER')),target=targets.find(p=>p.platform==='PAN_OS')||targets[0];setSourceProfile(source?.id||'');setSourceVersion(detected.version||source?.supported_versions[0]||'');setTargetProfile(target?.id||'');setTargetVersion(target?.supported_versions[0]||target?.target_versions?.[0]||'')}catch(reason){setError(String(reason))}}
  function contextChanged(update:()=>void){update();if(result)setStale(true)}
  async function run(){if(!selectedSource||!selectedTarget)return setError('Select source and target profiles.');setError('');setResult(undefined);setStale(false);try{const started=await api.start({source_text:sourceText,source_vendor:selectedSource.source_vendor,source_version:sourceVersion,source_profile:selectedSource.id,target_profile:selectedTarget.id,target_version:targetVersion,mappings:{}});setOperation({operation_id:started.operation_id,status:'RUNNING',stage:'VALIDATING_SOURCE',stages:[],elapsed_ms:0})}catch(reason){setError(String(reason))}}
  return <Workbench profiles={boot.profiles} maxConfigBytes={boot.maxConfigBytes} sourceText={sourceText} sourceName={sourceName} sourceProfile={sourceProfile} sourceVersion={sourceVersion} targetProfile={targetProfile} targetVersion={targetVersion} result={result} operation={operation} error={error} stale={stale} running={running} onLoad={load} onRun={run} onSourceProfile={value=>contextChanged(()=>setSourceProfile(value))} onSourceVersion={value=>contextChanged(()=>setSourceVersion(value))} onTargetProfile={value=>contextChanged(()=>{setTargetProfile(value);setTargetVersion(boot.profiles.find(p=>p.id===value)?.supported_versions[0]||'')})} onTargetVersion={value=>contextChanged(()=>setTargetVersion(value))} onRemove={()=>{setSourceText('');setSourceName('');setResult(undefined);setOperation(undefined);setStale(false)}}/>;
}