export const visualFixtureEnabled=typeof location!=='undefined'&&new URLSearchParams(location.search).get('demo')==='locked';
export const visualFixture={
  source:[
    '# Palo Alto Networks configuration example',
    'set deviceconfig system hostname PA-5220',
    'set deviceconfig system domain example.com',
    'set network interface ethernet1/1 layer3',
    'set network interface ethernet1/1 zone TRUST',
    'set network interface ethernet1/1 ip 10.8.1.1/24',
    'set network interface ethernet1/2 layer3',
    'set network interface ethernet1/2 zone UNTRUST',
    'set network interface ethernet1/2 ip 192.168.1.1/24',
    'set security zones security-zone TRUST',
    'set security zones security-zone UNTRUST',
    'set security address trust-host 10.0.1.10/32',
    'set security address-group Web-Servers static Trust-Host',
    'set security service HTTP port 80',
    'set security service HTTPS port 443',
    'set security policy rule Allow-Web from TRUST to UNTRUST',
    '    set source any',
    '    set destination any',
    '    set application web-browsing',
    '    set service application-default',
    '    set action allow',
    'set network virtual-router default',
    '    set network virtual-router default interface ethernet1/1',
    '    set network virtual-router default interface ethernet1/2',
    ...Array.from({length:96},(_,index)=>`set shared address fixture-${index+1} ip-netmask 198.51.100.${index%250+1}/32`),
  ].join('\n'),
  candidate:[
    '# Fortinet configuration (converted)',
    'config system global',
    '    set hostname PA-6000F',
    '    set domain example.com',
    'end',
    'config system interface',
    '    edit "port1"',
    '        set mode static',
    '        set ip 10.8.1.1 255.255.255.0',
    '        set allowaccess ping https ssh',
    '        set alias "TRUST"',
    '    next',
    '    edit "port2"',
    '        set mode static',
    '        set ip 192.168.1.1 255.255.255.0',
    '        set allowaccess ping https',
    '        set alias "UNTRUST"',
    '    next',
    'end',
    'config firewall zone',
    '    edit "TRUST"',
    '        set interface "port1"',
    '    next',
    'end',
    ...Array.from({length:96},(_,index)=>`config firewall address fixture-${index+1} 198.51.100.${index%250+1}/32`),
  ].join('\n'),
  legend:['1,776','420','183','62','36'],
  counts:[12,5,3,2,4],
  sourceStatuses:['','converted','converted','removed','modified','review','modified','review','removed','converted','converted','unsupported','converted','converted','converted','removed','','','','','','modified','modified','modified'],
  targetStatuses:['','converted','converted','modified','','removed','removed','','','','','','modified','','','','','review','','converted','converted','','',''],
};
